### ISSUE TITLE
Getting unhandled errors from nucleus

### ISSUE THREAD

**Issue by kurienzach** [nucleus-sh/nucleus-nodejs#8]
After integrating nucleus, I see a lot of errors of the below type on the nucleus dashboard. In fact 95% of the event that were generated for my test application was from nucleus. 

```
Error: EPERM: operation not permitted, rename 'C:\Users\Piyush\AppData\Roaming\testApp\nucleus.json.2685848482' -> 'C:\Users\Piyush\AppData\Roaming\testApp\nucleus.json'
    at Object.renameSync (fs.js:643:3)
    at Function.writeFileSync [as sync] (C:\Users\Piyush\AppData\Local\testApp\app-1.0.7\resources\app\.webpack\main\index.js:67678:8)
    at Conf._write (C:\Users\Piyush\AppData\Local\testApp\app-1.0.7\resources\app\.webpack\main\index.js:37307:21)
    at Conf.set store [as store] (C:\Users\Piyush\AppData\Local\testApp\app-1.0.7\resources\app\.webpack\main\index.js:37588:8)
    at Conf.set (C:\Users\Piyush\AppData\Local\testApp\app-1.0.7\resources\app\.webpack\main\index.js:37466:14)
    at Timeout.reportData [as _onTimeout] (C:\Users\Piyush\AppData\Local\testApp\app-1.0.7\resources\app\.webpack\main\index.js:65787:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by mtriff** [comment]
Also receiving these errors, likely due to the old version of the `conf` dependency. A version bump to the latest should fix this, as per this [pull request](https://github.com/sindresorhus/conf/pull/115) (and the discussion on the issue it links).

**Comment by vincelwt** [comment]
Hello! Thanks for reporting :) 
As @mtriff said, I updated the `conf` dependency to `7.1`. That should fix it. 
The latest version `3.0.7` with the fix is now on npm, a simple `npm update` should work.
